### ISSUE TITLE
How to use in Hassio

### ISSUE THREAD

**Issue by IamMikl** [Cheaterdev/sia-ha#2]
I've use hassio (HassOS + home assistant) and I don't understand how I can open/specify a right port for SIA custom_component.
Is it possible?

**Comment by Cheaterdev** [comment]
This integration connects to specific hub port. You need to specify hub port in configuration file only so HA can connect to.

**Comment by IamMikl** [comment]
Turned on "Connect on demand" - and it works even in hassio! Thanks!
