### ISSUE TITLE
Sia-ha status to homekit

### ISSUE THREAD

**Issue by vitaliy-kozlov** [Cheaterdev/sia-ha#8]
Hi, is there any solution to add Sia-ha statuses from ha to homekit ?

**Comment by Cheaterdev** [comment]
Hi! Have no HomeKit to test it - you can try creating a tempalte sensor through HomeKit supported device class:
https://www.home-assistant.io/integrations/binary_sensor/

**Comment by vitaliy-kozlov** [comment]
Fixed. Added to HomeKit using HA HomeKit bridge integration. Please close the issue.
